name: git action 构建镜像
run-name: ${{ github.actor }} 构建自定义镜像
on:
  push:
    paths:
      - 'eclipse-temurin-jdk11'
      - 'eclipse-temurin-jdk17'
      - 'jenkins-inbound'

jobs:
  bash-images-jdk11:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3.3.0

      - name: 登录dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.docker_user_name }}
          password: ${{ secrets.docker_password }}

      - name: build镜像
        if: ${{ success() }}
        run: |
          docker build --pull --no-cache -f eclipse-temurin-jdk11/Dockerfile -t fanq1213/eclipse-temurin:11.0.18_10-jre-alpine eclipse-temurin-jdk11
      - name: 推送镜像
        if: ${{ success() }}
        run: |
          docker push fanq1213/eclipse-temurin:11.0.18_10-jre-alpine
  bash-images-jdk17:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3.3.0

      - name: 登录dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.docker_user_name }}
          password: ${{ secrets.docker_password }}

      - name: build镜像
        if: ${{ success() }}
        run: |
          docker build --pull --no-cache -f eclipse-temurin-jdk17/Dockerfile -t fanq1213/eclipse-temurin:17.0.6_10-jre-alpine eclipse-temurin-jdk17
      - name: 推送镜像
        if: ${{ success() }}
        run: |
          docker push fanq1213/eclipse-temurin:17.0.6_10-jre-alpine
  jenkins-inbound:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3.3.0

      - name: 登录dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.docker_user_name }}
          password: ${{ secrets.docker_password }}

      - name: build镜像
        if: ${{ success() }}
        run: |
          docker build --pull --no-cache -f jenkins-inbound/Dockerfile -t fanq1213/jenkins-inbound:latest-jdk17 jenkins-inbound
      - name: 推送镜像
        if: ${{ success() }}
        run: |
          docker push fanq1213/jenkins-inbound:latest-jdk17

